name: "Promote Integration PR"
description: "This action promotes an integration PR from a 'draft' state to a 'ready' state."
inputs:
  integration_token:
    description: "GITHUB_TOKEN or a repo scoped PAT to access the integration repository."
    required: true
  integration_repository:
    description: "The integration repository to open a PR in"
    required: true
  integrated_component:
    description: "The name of the component being integrated"
    required: true
  transformation:
    description: "The bash transformation to perform on the integration repository (e.g. update version numbers)"
    required: true
  version:
    description: "The published artifact version"
    required: true
  slack_bot_token:
    description: "A token for posting notifications to Slack"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout the Integration Repository
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.integration_token }}
        repository: ${{ inputs.integration_repository }}
    - name: Edit the required repository files
      shell: bash
      run: ${{ inputs.transformation }}
    - name: Update PR
      id: update-pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.integration_token }}
        commit-message: "Update ${{ inputs.integrated_component }} version to '${{ inputs.version }}'"
        committer: badook Bot <badookbot@badook.ai>
        author: badook Bot <badookbot@badook.ai>
        branch: integration/${{ inputs.integrated_component }}/pr-${{ github.event.pull_request.number }}
        base: main
        title: "Update ${{ inputs.integrated_component }} version to '${{ inputs.version }}'"
        body: |
          This is an automated integration PR created for [${{ inputs.integrated_component }} PR #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}).
          The PR content can be found below.

          **Title:** ${{ github.event.pull_request.title }}

          **Body:**
          ${{ github.event.pull_request.body }}
        assignees: ${{ github.event.pull_request.user.login }}
        draft: false
    - name: Set PR as Ready for Review
      if: steps.update-pr.outputs.pull-request-operation == 'updated' # The PR will be created as ready for review if it was created at this stage
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.integration_token }}
      run: gh pr ready ${{ steps.update-pr.outputs.pull-request-number }}
    - name: Find Slack user
      id: find-slack-user
      if: inputs.slack_bot_token != ''
      uses: scribd/find-slack-user-action@v1
      with:
        slack-token: ${{ inputs.slack_bot_token }}
    - name: Send Slack DM
      if: steps.find-slack-user.outputs.found-user == 'true'
      uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
        GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        REF_URL: https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}
        TITLE: Deployment of v${{ inputs.chart-version }} Succeeded
      with:
        args: '{\"channel\":\"${{ steps.find-slack-user.outputs.member-id }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Your integration PR on <${{ steps.update-pr.outputs.pull-request-url }}|integration/${{ inputs.integrated_component }}/pr-${{ github.event.pull_request.number }}> is ready to review and merge\"}}]}'
