name: "Open Integration PR"
description: "This action opens an integration PR in a draft state."
inputs:
  github_token:
    description: "GITHUB_TOKEN or a repo scoped PAT to access the integrated repository."
    required: true
  integration_token:
    description: "GITHUB_TOKEN or a repo scoped PAT to access the integration repository."
    required: true
  integration_repository:
    description: "The integration repository to open a PR in"
    required: true
  integrated_component:
    description: "The name of the component being integrated"
    required: true
  transformation:
    description: "The bash transformation to perform on the integration repository (e.g. update version numbers)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout the Integration Repository
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.integration_token }}
        repository: ${{ inputs.integration_repository }}
    - name: Edit the required repository files
      shell: bash
      run: ${{ inputs.transformation }}
    - name: Set Assignee
      id: set-assignee
      shell: bash
      run: |
        ASSIGNEE=$(if [[ "${{ github.event.pull_request.user.login }}" != "dependabot[bot]" ]]; then echo "${{ github.event.pull_request.user.login }}"; else echo ""; fi)
        echo "::set-output name=assignee::$ASSIGNEE"
    - name: Create Draft PR
      id: create-draft-pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ inputs.integration_token }}
        commit-message: "Update ${{ inputs.integrated_component }} version to 'pr-${{ github.event.pull_request.number }}'"
        committer: badook Bot <badookbot@badook.ai>
        author: badook Bot <badookbot@badook.ai>
        branch: integration/${{ inputs.integrated_component }}/pr-${{ github.event.pull_request.number }}
        base: main
        title: "Update ${{ inputs.integrated_component }} version to 'pr-${{ github.event.pull_request.number }}'"
        body: |
          This is an automated integration PR created for  [${{ inputs.integrated_component }} PR #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}).
          It will be updated and promoted to a non-draft status once that PR is merged.
        labels: semver:patch
        assignees: ${{ steps.set-assignee.outputs.assignee }}
        draft: true

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: Integration PR
        token: ${{ inputs.github_token }}
    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Integration PR :zap:
          An integration PR for this PR was created [here](${{ steps.create-draft-pr.outputs.pull-request-url }})
        edit-mode: replace
        token: ${{ inputs.github_token }}
