name: Publish

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  tag-version:
    name: Tag Version
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Tag Version
        id: tag-version
        uses: ./tag-version
        with:
          dry_run: false
      - name: Get Major Version
        id: get-major
        run: |
          major=$(echo "v${{ steps.tag-version.outputs.version }}" | sed 's/\..*//')
          echo "::set-output name=major::$major"
      - name: Tag Major Version
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.get-major.outputs.major }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
