name: Publish

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  tag-version:
    name: Tag Version
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Tag Version
        uses: ./tag-version
        with:
          dry_run: false
