name: Lint & Test Actions

on: [ pull_request ]

jobs:
  test:
    name: Lint & Test Actions
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Install Poetry
        uses: ./cached-install-poetry
      - name: Pre-Commit
        uses: ./cached-pre-commit-run
      - name: Poetry Install
        uses: ./cached-poetry-install-dependencies
