name: Lint

on: [ pull_request ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Load pre-commit cache
        id: cached-pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run Pre-Commit Checks
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  test-cached-install-poetry:
    name: 'Test "Cached Install Poetry"'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
      - name: Run Action
        uses: ./cached-install-poetry

  test-cached-poetry-install-dependencies:
    name: 'Test "Cached Poetry Install Dependencies"'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
      - name: Run Action
        uses: ./cached-poetry-install-dependencies
